# ---------------------------------------------------------------------
# link generation : 
# - https://static.brandonpotter.com/kubernetes/DeploymentBuilder.html
---
# 1) Create the Secret for private registry :
#    - kubectl create secret docker-registry regcred --docker-server=registry.hub.docker.com /
#      --docker-username=mchahdi --docker-password=*********
---
# 2) Print & Ckeck the created Secret yaml file :
#    - kubectl get secret regcred --output=yaml
---
# 3) Deployment of the Gateway Microservice:
#    - kubectl apply -f k8s/eth-platform/deployment-eureka.yaml
# ---------------------------------------------------------------------
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka-ns
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka-ns
    spec:
      containers:
        - name: scc-eureka-ems
          image: >-
            registry.hub.docker.com/mchahdi/scc-platform:eth-eureka-ems-0.0.1-SNAPSHOT
          ports:
            - containerPort: 3380
      imagePullSecrets:
        - name: regcred       

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    name: eureka-service
spec:
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 3380
      
  selector:
    app: eureka-ns
  type: LoadBalancer